package com.github.autodiag2.elm327emu.sim.serial

import android.util.Log
import com.github.autodiag2.elm327emu.BuildConfig
import com.github.autodiag2.elm327emu.LogLevel
import com.github.autodiag2.elm327emu.sim.serial.CustomController.*
import kotlinx.coroutines.*
import kotlinx.coroutines.channels.Channel
import java.io.ByteArrayOutputStream
import java.io.IOException
import java.util.concurrent.LinkedBlockingQueue
import java.util.concurrent.TimeUnit
import java.util.concurrent.TimeoutException
import com.github.autodiag2.elm327emu.sim.EmuInterface

class StateMachine(
    private val controller: CustomController,
    private val listener: Listener? = null,
    LOG_TAG: String = "sim.serial.StateMachine"
) : EmuInterface(LOG_TAG = LOG_TAG), EmuInterface.Provider {

    enum class State {
        READY,
        WAIT,
        FINISHED
    }

    data class Path(
        val id: Int,
        var origin: BlockController,
        var block: BlockController,
        var state: State = State.READY,
        var wakeTime: Long = 0L
    )

    private sealed class Event {
        data object Start : Event()
        data object Stop : Event()
        data object ModelChanged : Event()
        data class Receive(val bytes: ByteArray) : Event()
        data class Timeout(val pathId: Int) : Event()
        data object Tick : Event()
    }

    interface Listener {
        fun onBlockStateChanged(
            block: BlockController,
            state: BlockController.State
        )
    }

    private val scope =
        CoroutineScope(
            Dispatchers.IO +
                SupervisorJob()
        )

    private val events =
        Channel<Event>(Channel.UNLIMITED)

    private val paths =
        mutableListOf<Path>()

    private var stateJob: Job? = null
    private var inputJob: Job? = null

    /*
     * Data received from a bridge through EmuInterface.send().
     *
     * Bridge -> StateMachine
     */
    private val sendQueue =
        LinkedBlockingQueue<ByteArray>()

    /*
     * Data generated by SEND blocks and returned to a bridge
     * through EmuInterface.recv().
     *
     * StateMachine -> Bridge
     */
    private val recvQueue =
        LinkedBlockingQueue<ByteArray>()

    /*
     * Current reply being consumed by recv().
     *
     * A bridge may provide a buffer smaller than the reply generated
     * by a SEND block, so the remaining bytes must be preserved.
     */
    private var recvCurrent: ByteArray? = null
    private var recvCurrentOffset = 0

    private var nextPathId = 1

    @Volatile
    private var running = false

    init {
        stateJob =
            scope.launch {
                stateLoop()
            }
    }

    override fun getEmu(): EmuInterface {
        return this
    }

    override fun setEmu(emu: EmuInterface) {
        throw IllegalArgumentException("not implemented")
    }

    override fun resetEmu() {
    }

    private fun findPath(blockAny: Any): Path? {
        var blockId = -1
        if ( blockAny is Int ) {
            blockId = blockAny
        } else if ( blockAny is BlockController ) {
            blockId = blockAny.id
        }
        return paths.find { it.block.id == blockId }
    }
    private fun mergePathAt(block: BlockController, incoming: Path): Path {
        val existing = paths.find { it.block.id == block.id }

        if (existing != null) {
            logDebug(
                "MERGE PATH ${incoming.id} INTO PATH ${existing.id} " +
                "AT BLOCK ${block.id}"
            )

            paths.remove(incoming)
            return existing
        }

        return incoming
    }
    private fun setBlockStateBackPropagate(
        block: BlockController
    ) {
        if (block.type == BlockController.Type.CONTAINER) {
            val result =
                run {
                    var atLeastOneInProgress = false
                    var allSuccess = true
                    var atLeastOneFailed = false

                    for (childId in block.children) {
                        val child =
                            resolveBlock(childId)

                        if (
                            child.state ==
                            BlockController.State.IN_PROGRESS
                        ) {
                            atLeastOneInProgress = true
                        }

                        if (
                            child.state ==
                            BlockController.State.FAILED
                        ) {
                            atLeastOneFailed = true
                        }

                        allSuccess =
                            allSuccess &&
                                child.state ==
                                BlockController.State.SUCCESS
                    }

                    when {
                        allSuccess ->
                            BlockController.State.SUCCESS

                        atLeastOneInProgress ->
                            BlockController.State.IN_PROGRESS

                        atLeastOneFailed ->
                            BlockController.State.FAILED

                        else ->
                            null
                    }
                }

            if (result != null) {
                block.state = result

                val path =
                    paths.find {
                        it.block == block
                    }

                if (
                    result ==
                    BlockController.State.SUCCESS ||
                    result ==
                    BlockController.State.FAILED
                ) {
                    if (path != null) {
                        advance(path)
                    }
                }
            } else {
                block.state =
                    BlockController.State.IN_PROGRESS
            }
        }

        val parent =
            block.parent

        if (parent != null) {
            setBlockStateBackPropagate(parent)
        }
    }

    private fun setBlockState(
        block: BlockController,
        state: BlockController.State
    ) {
        block.state = state
        setBlockStateBackPropagate(block)
        listener?.onBlockStateChanged(
            block,
            state
        )
    }

    /**
     * Called by a bridge when data is received from the client.
     *
     * Bridge -> StateMachine.
     */
    override fun send(
        buffer: ByteArray,
        size: Int,
        timeoutMs: Long
    ) {
        if (size <= 0) {
            return
        }

        if (size > buffer.size) {
            throw IndexOutOfBoundsException(
                "size=$size buffer.size=${buffer.size}"
            )
        }

        val data =
            buffer.copyOf(size)

        logDebug(
            "send ${size} bytes: " +
                data.toDebugString()
        )

        sendQueue.offer(data)
    }

    /**
     * Called by a bridge to obtain data generated by a SEND block.
     *
     * StateMachine -> Bridge.
     */
    override fun recv(
        buffer: ByteArray,
        timeoutMs: Long
    ): Int {

        if (buffer.isEmpty()) {
            return 0
        }

        while (true) {

            val current =
                recvCurrent

            if (
                current != null &&
                recvCurrentOffset < current.size
            ) {

                val count =
                    minOf(
                        buffer.size,
                        current.size - recvCurrentOffset
                    )

                System.arraycopy(
                    current,
                    recvCurrentOffset,
                    buffer,
                    0,
                    count
                )

                recvCurrentOffset += count

                if (
                    recvCurrentOffset >=
                    current.size
                ) {
                    recvCurrent = null
                    recvCurrentOffset = 0
                }

                logDebug(
                    "recv $count bytes: " +
                        buffer.copyOf(count).toDebugString()
                )

                return count
            }

            recvCurrent = null
            recvCurrentOffset = 0

            val data =
                try {
                    if (timeoutMs <= 0L) {
                        recvQueue.take()
                    } else {
                        recvQueue.poll(
                            timeoutMs,
                            TimeUnit.MILLISECONDS
                        ) ?: return 0
                    }
                } catch (e: InterruptedException) {
                    Thread.currentThread().interrupt()

                    throw IOException(
                        "Receive interrupted",
                        e
                    )
                }

            if (data.isEmpty()) {
                return -1
            }

            recvCurrent = data
            recvCurrentOffset = 0
        }
    }

    private fun startInputReader() {
        inputJob?.cancel()

        inputJob =
            scope.launch {
                try {
                    val pending =
                        ByteArrayOutputStream()

                    while (
                        isActive &&
                        running
                    ) {

                        val chunk =
                            try {
                                sendQueue.take()
                            } catch (e: InterruptedException) {
                                Thread.currentThread().interrupt()
                                break
                            }

                        if (chunk.isEmpty()) {
                            continue
                        }

                        logDebug(
                            "received ${chunk.size} bytes: " +
                                chunk.toDebugString()
                        )

                        pending.write(chunk)

                        while (true) {
                            val data =
                                pending.toByteArray()

                            val end =
                                findReceiveDelimiter(
                                    data
                                )

                            if (end < 0) {
                                break
                            }

                            val message =
                                data.copyOfRange(
                                    0,
                                    end
                                )

                            logDebug(
                                "Input message: " +
                                    message.toDebugString()
                            )

                            events.send(
                                Event.Receive(
                                    message
                                )
                            )

                            pending.reset()

                            if (end < data.size) {
                                pending.write(
                                    data,
                                    end,
                                    data.size - end
                                )
                            }
                        }
                    }

                } catch (_: CancellationException) {
                    // Normal shutdown.
                } catch (e: Exception) {
                    appendLog(
                        "input reader error: ${e.message}",
                        LogLevel.ERROR
                    )

                    events.trySend(
                        Event.Stop
                    )
                }
            }
    }

    private fun findReceiveDelimiter(
        data: ByteArray
    ): Int {
        for (i in data.indices) {
            if (
                data[i] !=
                '\r'.code.toByte()
            ) {
                continue
            }

            if (
                i + 1 < data.size &&
                data[i + 1] ==
                '\n'.code.toByte()
            ) {
                return i + 2
            }

            return i + 1
        }

        return -1
    }

    fun getString(
        resId: Int,
        vararg formatArgs: Any?
    ): String {
        return controller.getString(
            resId,
            *formatArgs.map {
                it ?: ""
            }.toTypedArray()
        )
    }

    fun appendLog(
        text: String,
        level: LogLevel = LogLevel.DEBUG
    ) {
        controller.activity.appendLog(
            text,
            level
        )
    }

    fun start() {
        events.trySend(
            Event.Start
        )
    }

    fun stop() {
        logDebug("STOPPING")

        events.trySend(
            Event.Stop
        )
    }

    fun customModelChanged() {
        events.trySend(
            Event.ModelChanged
        )
    }

    private suspend fun stateLoop() {
        for (event in events) {
            when (event) {
                Event.Start -> {
                    handleStart()
                }

                Event.Stop -> {
                    handleStop()
                }

                Event.ModelChanged -> {
                    handleModelChanged()
                }

                is Event.Receive -> {
                    handleReceive(
                        event.bytes
                    )
                }

                is Event.Timeout -> {
                    handleTimeout(
                        event.pathId
                    )
                }

                Event.Tick -> {
                    handleTick()
                }
            }
        }
    }

    fun containerGetRootBlocks(
        container: BlockController? = null
    ): List<BlockController> {

        val linkedBlockIds =
            controller.links
                .map {
                    it.to
                }
                .toSet()

        return controller.blocks
            .filter { block ->
                block.id !in linkedBlockIds &&
                    block.parent == container
            }
    }

    private suspend fun handleStart() {
        handleStop()

        controller.resetBlockStates()

        val initialBlocks = containerGetRootBlocks()

        logDebug(
            "Execution roots: " +
                initialBlocks.joinToString(", ") {
                    it.id.toString()
                }
        )

        running = initialBlocks.isNotEmpty()

        for (block in initialBlocks) {
            createPath(block)
        }

        if (running) {
            startInputReader()
            handleTick()
        }
    }

    private fun handleStop() {
        running = false

        inputJob?.cancel()
        inputJob = null

        paths.clear()
        nextPathId = 1

        sendQueue.clear()
        recvQueue.clear()

        recvCurrent = null
        recvCurrentOffset = 0

        logDebug("STOPPED")
    }

    /**
     * Synchronize the running state machine with the current
     * CustomController model.
     *
     * This method is called only from stateLoop(), therefore
     * paths cannot be modified concurrently with execution.
     */
    private suspend fun handleModelChanged() {
        if (!running) {
            return
        }

        logDebug(
            "Custom model changed"
        )

        val currentBlocks =
            controller.blocks
                .associateBy {
                    it.id
                }

        /*
         * Remove paths whose current block no longer exists.
         */
        val removedPaths =
            paths.filter {
                !currentBlocks.containsKey(
                    it.block.id
                )
            }

        for (path in removedPaths) {
            logDebug(
                "Removing path=${path.id}: " +
                    "block=${path.block.id} was deleted"
            )

            setBlockState(
                path.block,
                BlockController.State.IDLE
            )

            path.state = State.FINISHED
            logDebug("PATH FINISHED ${path.id}")
        }

        paths.removeAll {
            it.state == State.FINISHED
        }

        /*
         * Keep only one active path per current block.
         *
         * This prevents repeated model changes from creating
         * duplicate paths for the same execution root.
         */
        val duplicatePaths =
            mutableSetOf<Int>()

        val duplicatePathObjects =
            paths.filter { path ->
                !duplicatePaths.add(
                    path.block.id
                )
            }

        for (path in duplicatePathObjects) {
            logDebug(
                "Removing duplicate path=${path.id}: " +
                    "block=${path.block.id}"
            )

            path.state = State.FINISHED
            logDebug("PATH FINISHED ${path.id}")
        }

        paths.removeAll {
            it.state == State.FINISHED
        }

        /*
         * Recalculate execution roots.
         *
         * A root is a block with no incoming execution link.
         */
        val linkedBlockIds =
            controller.links
                .map {
                    it.to
                }
                .toSet()

        val rootBlocks =
            controller.blocks
                .filter {
                    it.id !in linkedBlockIds
                }

        /*
         * Add roots which do not currently have a path.
         *
         * This is important when a new block is added, or when
         * removing an incoming link turns an existing block into
         * a root.
         */
        val pathBlockIds =
            paths
                .map {
                    it.block.id
                }
                .toMutableSet()

        for (root in rootBlocks) {
            if (
                pathBlockIds.add(
                    root.id
                )
            ) {
                logDebug(
                    "Model change added execution root: " +
                        "block=${root.id}"
                )

                createPath(root)
            }
        }

        /*
         * Update paths whose current block changed while the
         * model was being edited.
         *
         * DELAY:
         * restart the delay using the new timeout.
         *
         * RECV:
         * root receives remain infinite;
         * non-root receives get a new timeout.
         *
         * SEND and CONTAINER:
         * their changed parameters are used the next time
         * the block executes, so no state change is necessary.
         */
        val now =
            System.currentTimeMillis()

        val linkedIds =
            controller.links
                .map {
                    it.to
                }
                .toSet()

        for (path in paths.toList()) {
            if (
                !currentBlocks.containsKey(
                    path.block.id
                )
            ) {
                continue
            }

            val block =
                currentBlocks[
                    path.block.id
                ] ?: continue

            when (path.state) {
                State.WAIT -> {
                    if (
                        block.type !=
                        BlockController.Type.DELAY
                    ) {
                        path.state =
                            State.READY

                        path.wakeTime = 0L

                        setBlockState(
                            block,
                            BlockController.State.IDLE
                        )

                        continue
                    }

                    if (
                        block.type !=
                        BlockController.Type.RECV
                    ) {
                        path.state =
                            State.READY

                        path.wakeTime = 0L

                        setBlockState(
                            block,
                            BlockController.State.IDLE
                        )

                        continue
                    }

                    path.wakeTime =
                        now +
                            block.timeoutMs

                    logDebug(
                        "Updated DELAY path=" +
                            "${path.id} " +
                            "block=${block.id} " +
                            "wakeTime=${path.wakeTime}"
                    )
                }

                State.READY,
                State.FINISHED -> {
                    // Nothing to update.
                }
            }
        }

        /*
         * If there are no paths left, stop execution.
         */
        if (paths.isEmpty()) {
            logDebug(
                "No execution paths remain after model change"
            )

            running = false

            inputJob?.cancel()
            inputJob = null

            return
        }

        /*
         * Make sure the execution loop continues after a model
         * change, including when a new root was added.
         */
        handleTick()
    }

    private suspend fun handleTick() {
        if (!running) {
            return
        }

        val now =
            System.currentTimeMillis()

        for (path in paths.toList()) {
            val block = path.block
            when (path.state) {
                State.READY -> {
                    execute(path)
                }

                State.WAIT -> {
                    if (
                        now >=
                        path.wakeTime
                    ) {
                        when ( block.type ) {
                            BlockController.Type.DELAY -> {
                                path.state =
                                    State.READY
                                
                                setBlockState(
                                    path.block,
                                    BlockController.State.SUCCESS
                                )
        
                                advance(path)
                            }
                            BlockController.Type.RECV -> {
                                events.trySend(
                                    Event.Timeout(
                                        path.id
                                    )
                                )
                            }
                            else -> {
                            
                            }
                        }
                    }
                }

                State.FINISHED -> {
                    paths.remove(path)
                }
            }
        }

        paths.removeAll {
            it.state ==
                State.FINISHED
        }

        if (paths.isEmpty()) {
            running = false

            inputJob?.cancel()
            inputJob = null

            return
        }

        scope.launch {
            delay(10L)

            if (
                isActive &&
                running
            ) {
                events.trySend(
                    Event.Tick
                )
            }
        }
    }

    private fun isGate(
        block: BlockController
    ): Boolean {
        return block.type == BlockController.Type.AND ||
            block.type == BlockController.Type.OR ||
            block.type == BlockController.Type.XOR ||
            block.type == BlockController.Type.NOT
    }

    private fun gateInputs(gate: BlockController): List<BlockController> {
        return controller.links
            .filter { it.to == gate.id }
            .mapNotNull { link ->
                controller.blocks.find { it.id == link.from }
            }
    }

    private fun evaluateGatePath(path: Path) {
        val result = evaluateGate(path.block)

        when (result) {
            BlockController.State.SUCCESS -> {
                setBlockState(
                    path.block,
                    BlockController.State.SUCCESS
                )

                advance(path)
            }

            BlockController.State.FAILED -> {
                setBlockState(
                    path.block,
                    BlockController.State.FAILED
                )

                advance(path)
            }

            null -> {
                path.state = State.WAIT

                setBlockState(
                    path.block,
                    BlockController.State.IN_PROGRESS
                )

                logDebug(
                    "GATE WAIT ${path.block.id}"
                )
            }

            else -> {
            }
        }
    }

    private fun evaluateGate(
        block: BlockController
    ): BlockController.State? {

        val inputs = gateInputs(block)

        val successCount =
            inputs.count {
                it.state == BlockController.State.SUCCESS
            }

        val failedCount =
            inputs.count {
                it.state == BlockController.State.FAILED
            }

        val finishedCount = successCount + failedCount
        if ( finishedCount != inputs.size )  {
            return null
        }

        return when (block.type) {

            BlockController.Type.AND -> {
                when {
                    failedCount > 0 ->
                        BlockController.State.FAILED

                    successCount == inputs.size ->
                        BlockController.State.SUCCESS

                    else ->
                        null
                }
            }

            BlockController.Type.OR -> {
                when {
                    successCount > 0 ->
                        BlockController.State.SUCCESS

                    finishedCount == inputs.size ->
                        BlockController.State.FAILED

                    else ->
                        null
                }
            }

            BlockController.Type.XOR -> {
                when {
                    successCount > 1 ->
                        BlockController.State.FAILED

                    successCount == 1 ->
                        BlockController.State.SUCCESS

                    finishedCount == inputs.size ->
                        BlockController.State.FAILED

                    else ->
                        null
                }
            }

            BlockController.Type.NOT -> {
                when {
                    successCount > 0 ->
                        BlockController.State.FAILED

                    failedCount > 0 ->
                        BlockController.State.SUCCESS

                    else ->
                        null
                }
            }

            else ->
                null
        }
    }

    private suspend fun execute(
        path: Path
    ) {
        val block =
            path.block

        val blockId =
            block.id

        val blockType =
            block.type

        logDebug("EXEC $blockType($blockId) path=${path.id}")

        setBlockState(
            block,
            BlockController.State.IN_PROGRESS
        )

        try {
            when (blockType) {
                BlockController.Type.DELAY -> {
                    path.wakeTime =
                        System.currentTimeMillis() +
                            block.timeoutMs

                    path.state = State.WAIT
                }

                BlockController.Type.SEND -> {
                    executeSend(block)

                    setBlockState(
                        block,
                        BlockController.State.SUCCESS
                    )

                    advance(path)
                }

                BlockController.Type.RECV -> {
                    val linkedBlockIds =
                        controller.links
                            .map {
                                it.to
                            }
                            .toSet()

                    val isRoot =
                        block.id !in linkedBlockIds

                    if (isRoot) {
                        path.wakeTime =
                            Long.MAX_VALUE
                    } else {
                        path.wakeTime =
                            System.currentTimeMillis() +
                                block.timeoutMs
                    }

                    path.state = State.WAIT
                }

                BlockController.Type.CONTAINER -> {
                    setBlockState(
                        block,
                        BlockController.State.IN_PROGRESS
                    )

                    val childRoots = containerGetRootBlocks(block)

                    if (childRoots.isEmpty()) {
                        setBlockState(
                            block,
                            BlockController.State.SUCCESS
                        )

                        advance(path)
                    } else {
                        for (child in childRoots) {
                            createPath(child)
                        }
                        path.state = State.WAIT
                    }
                }
                BlockController.Type.AND,
                BlockController.Type.OR,
                BlockController.Type.XOR,
                BlockController.Type.NOT -> {
                    evaluateGatePath(path)
                }
            }
        } catch (
            e: TimeoutCancellationException
        ) {
            logDebug("EXEC $blockType($blockId) TIMEOUT(${block.timeoutMs}ms)")

            setBlockState(
                block,
                BlockController.State.FAILED
            )

            path.state = State.FINISHED
            logDebug("PATH FINISHED")
        } catch (e: Exception) {
            logDebug("EXEC $blockType($blockId) EXCEPTION(${e.message})")
            setBlockState(
                block,
                BlockController.State.FAILED
            )

            path.state = State.FINISHED
            logDebug("PATH FINISHED")
        }

        logDebug("EXEC END $blockType($blockId) path=${path.id}")
    }

    private fun isDescendant(
        block: BlockController,
        container: BlockController
    ): Boolean {
        var current = block.parent

        while (current != null) {
            if (current === container) {
                return true
            }

            current = current.parent
        }

        return false
    }

    private suspend fun executeSend(
        block: BlockController
    ) {
        var text =
            block.text

        if (
            block.includeEol &&
            !text.endsWith("\r\n")
        ) {
            text += "\r\n"
        }

        val bytes =
            if (block.interpretEscapes) {
                BlockController.parseEscapedBytes(
                    text
                )
            } else {
                text.toByteArray(
                    Charsets.ISO_8859_1
                )
            }

        logDebug("EXEC SEND bytes=" + bytes.toDebugString())

        recvQueue.put(
            bytes.copyOf()
        )

        logDebug("EXEC SEND QUEUE -> ")
    }

    private fun ByteArray.toDebugString(): String {
        return buildString {
            for (
                byte in this@toDebugString
            ) {
                val value =
                    byte.toInt() and 0xFF

                when (value) {
                    0x0D ->
                        append("\\r")

                    0x0A ->
                        append("\\n")

                    0x09 ->
                        append("\\t")

                    0x00 ->
                        append("\\0")

                    0x5C ->
                        append("\\\\")

                    else -> {
                        if (
                            value in
                            0x20..0x7E
                        ) {
                            append(
                                value.toChar()
                            )
                        } else {
                            append(
                                "\\x%02X".format(
                                    value
                                )
                            )
                        }
                    }
                }
            }
        }
    }

    private suspend fun handleReceive(
        bytes: ByteArray
    ) {
        if (!running) {
            return
        }

        logDebug("EXEC RECV ${bytes.size} bytes: " + bytes.toDebugString())

        val waitingPaths =
            paths
                .filter {
                    it.state == State.WAIT &&
                    it.block.type == BlockController.Type.RECV
                }
                .toList()

        for (path in waitingPaths) {
            if (
                path.block.recvMatches(
                    bytes
                )
            ) {
                logDebug("EXEC RECV MATCH ${path.block.type}(${path.block.id}) path=${path.id}")

                setBlockState(
                    path.block,
                    BlockController.State.SUCCESS
                )

                advance(path)
            } else {
                val linkedBlockIds =
                    controller.links
                        .map {
                            it.to
                        }
                        .toSet()

                val isRoot =
                    path.block.id !in
                        linkedBlockIds

                if (isRoot) {
                    setBlockState(
                        path.block,
                        BlockController.State.IN_PROGRESS
                    )

                    logDebug("EXEC RECV ${path.block.type}(${path.block.id}) path=${path.id} keeping WAIT_RECV")
                } else {
                    setBlockState(
                        path.block,
                        BlockController.State.FAILED
                    )

                    path.state = State.FINISHED
                    logDebug("PATH FINISHED")
                }
            }
        }

        paths.removeAll {
            it.state == State.FINISHED
        }

        if (paths.isEmpty()) {
            running = false

            inputJob?.cancel()
            inputJob = null

            return
        }

        handleTick()
    }

    private fun handleTimeout(
        pathId: Int
    ) {
        if (!running) {
            return
        }

        val path =
            paths.find {
                it.id == pathId
            } ?: return

        if (
            path.state !=
            State.WAIT
        ) {
            return
        }

        val exception =
            TimeoutException(
                "RECV timeout for " +
                    "block=${path.block.id}"
            )

        appendLog(
            exception.message
                ?: "RECV timeout",
            LogLevel.ERROR
        )

        logDebug(
            "RECV TIMEOUT " +
                "path=${path.id} " +
                "block=${path.block.id}"
        )

        setBlockState(
            path.block,
            BlockController.State.FAILED
        )

        path.state = State.FINISHED
        logDebug("PATH FINISHED ${path.id}")

        paths.removeAll {
            it.state == State.FINISHED
        }

        if (paths.isEmpty()) {
            running = false

            inputJob?.cancel()
            inputJob = null
        }
    }

    private fun advance(
        path: Path
    ) {
        logDebug(
            "ADVANCE ${path.block.type}(${path.block.id}) path=${path.id}"
        )

        val fromId = path.block.id

        val nextBlocks =
            controller.links
                .filter {
                    it.from == fromId
                }
                .mapNotNull { link ->
                    controller.blocks.find {
                        it.id == link.to
                    }
                }

        if (nextBlocks.isEmpty()) {
            onPathEnded(path)
            return
        }

        val firstBlock = nextBlocks.first()

        if (isGate(firstBlock)) {
            val existingPath =
                findPath(firstBlock)

            if (existingPath != null &&
                existingPath !== path
            ) {
                logDebug(
                    "MERGE PATH ${path.id} INTO GATE " +
                        "${existingPath.id} " +
                        "BLOCK ${firstBlock.id}"
                )

                path.state = State.FINISHED

                evaluateGatePath(existingPath)

                return
            }
        }

        path.block = firstBlock
        path.state = State.READY

        for (
            block in
            nextBlocks.drop(1)
        ) {
            if (isGate(block)) {
                val existingPath =
                    findPath(block)

                if (existingPath != null) {
                    logDebug(
                        "MERGE NEW BRANCH INTO GATE " +
                            "${existingPath.id} " +
                            "BLOCK ${block.id}"
                    )

                    evaluateGatePath(existingPath)
                } else {
                    createPath(block)
                }
            } else {
                createPath(block)
            }
        }
    }

    private fun onPathEnded(path: Path) {
        path.state = State.FINISHED
        logDebug("PATH FINISHED ${path.id}")
    }

    private fun resolveBlockId(
        id: Int
    ): BlockController? {
        return controller.blocks.find {
            it.id == id
        }
    }

    private fun resolveBlock(blockAny: Any): BlockController {
        return when (blockAny) {
            is Int ->
                resolveBlockId(blockAny)
                    ?: throw IllegalArgumentException(
                        "Block not found: id=$blockAny"
                    )

            is BlockController ->
                blockAny

            else ->
                throw IllegalArgumentException(
                    "Invalid block type: " +
                        "${blockAny::class.java.name}"
                )
        }
    }

    private fun createPath(
        blockAny: Any
    ) {
        val block = resolveBlock(blockAny)
        val path =
            Path(
                id = nextPathId++,
                block = block,
                origin = block
            )

        paths.add(path)

        logDebug("CREATE PATH ${block.type}(${block.id}) path=${path.id}")
    }

    fun isRunning(): Boolean {
        return running
    }

    private fun String.escape(): String {
        return this
            .replace(
                "\\",
                "\\\\"
            )
            .replace(
                "\r",
                "\\r"
            )
            .replace(
                "\n",
                "\\n"
            )
            .replace(
                "\t",
                "\\t"
            )
    }

    fun destroy() {
        running = false

        inputJob?.cancel()
        inputJob = null

        stateJob?.cancel()
        stateJob = null

        events.close()
        scope.cancel()
    }
}